@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue May 17 17:45:55 +0200 2022
REM SW Build 2729669 on Thu Dec  5 04:49:17 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 3780155d015e495ab8c0c250ce425d7e --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot LSFR_tb_behav xil_defaultlib.LSFR_tb -log elaborate.log"
call xelab  -wto 3780155d015e495ab8c0c250ce425d7e --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot LSFR_tb_behav xil_defaultlib.LSFR_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
