@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Mar 01 11:16:35 +0100 2022
REM SW Build 2729669 on Thu Dec  5 04:49:17 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim cnt_bin_tb_behav -key {Behavioral:sim_1:Functional:cnt_bin_tb} -tclbatch cnt_bin_tb.tcl -view D:/Documents/xjasek15/MPC-PLD/04_PC/counter/cnt_bin_tb_behav.wcfg -log simulate.log"
call xsim  cnt_bin_tb_behav -key {Behavioral:sim_1:Functional:cnt_bin_tb} -tclbatch cnt_bin_tb.tcl -view D:/Documents/xjasek15/MPC-PLD/04_PC/counter/cnt_bin_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
