webtalk_init -webtalk_dir D:/Documents/xjasek15/MPC-PLD/08_PC/PWM_8C/PWM_8C.sim/sim_1/behav/xsim/xsim.dir/pwm_driver_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 28 09:56:11 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2729669" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "175231130_1777487917_210548723_104" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d6382a03-deed-4d04-9ad0-8c24b7d8ae89" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "abf5b423eb8d4050aff7cf733601d8b0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "28" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-3550 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3300 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "51 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6932_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2878908945 -regid "175231130_1777487917_210548723_104" -xml D:/Documents/xjasek15/MPC-PLD/08_PC/PWM_8C/PWM_8C.sim/sim_1/behav/xsim/xsim.dir/pwm_driver_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Documents/xjasek15/MPC-PLD/08_PC/PWM_8C/PWM_8C.sim/sim_1/behav/xsim/xsim.dir/pwm_driver_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Documents/xjasek15/MPC-PLD/08_PC/PWM_8C/PWM_8C.sim/sim_1/behav/xsim/xsim.dir/pwm_driver_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
