@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Mar 21 09:56:23 +0100 2022
REM SW Build 2729669 on Thu Dec  5 04:49:17 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto edfdffeb3007469888a362996319aabb --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot UART_Tx_block_tb_behav xil_defaultlib.UART_Tx_block_tb -log elaborate.log"
call xelab  -wto edfdffeb3007469888a362996319aabb --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot UART_Tx_block_tb_behav xil_defaultlib.UART_Tx_block_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
